name: calculatorProject
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    privileged: true
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PWD}   
      MARIADB_DATABASE: ${MYSQL_DB}             
      MARIADB_USER: ${MYSQL_USER}               
      MARIADB_PASSWORD: ${MYSQL_PWD}
    ports:
      - "${DB_PORT}:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PWD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mariadb_data:/var/lib/mysql
    
  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./db/migrations:/flyway/sql
    command: "migrate"
    environment:
      FLYWAY_URL: ${FLYWAY_URL}
      FLYWAY_USER: ${MYSQL_USER}
      FLYWAY_PASSWORD: ${MYSQL_PWD}
  
  api:
    image: ghcr.io/${GH_REPO}-api:staging
    container_name: calculator_api
    restart: always
    depends_on:
      - mariadb
    environment:
      DB_CON_STR: ${DB_CON_STR} 
    ports:
      - "${API_PORT}:8080"
  
  react:
    image: ghcr.io/${GH_REPO}-react:staging
    container_name: calculator_react
    restart: always
    ports:
      - "${REACT_PORT}:80"
    environment:
      VITE_API_URL: ${VITE_API_URL}
    depends_on:
      - api

volumes:
  mariadb_data: